  generate-actions-workflow:
    name: Generate The Actions Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Pre-Commit
        run: |
          pip install -U pip
          pip install pre-commit
          pre-commit install

      - name: Generate Workflow Actions
        run: |
          pre-commit run -av generate-actions-workflow
